#!/bin/bash

gcc -o plain_tise -Wall -Wextra tise.c 
gcc -o O1_tise -Wall -Wextra -O1 tise.c 
gcc -o O2_tise -Wall -Wextra -O2 tise.c 
gcc -o O3_tise -Wall -Wextra -O3 tise.c 
gcc -o Ofast_tise -Wall -Wextra -Ofast tise.c 